package com.themistra.auth.apikey;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * A merchant API key (R30, L7). {@code accountId} is a plain column, never a JPA relation to
 * {@code Account} — this module never imports that entity (L12). {@code keyHash} is the SHA-256
 * hex digest of the full {@code ck_live_<suffix>.<secret>} string; the plaintext key itself is
 * never persisted anywhere.
 *
 * <p>Deliberately has no mutators for {@code lastUsedAt}, {@code revokedAt}, or {@code name} —
 * T23 provides only the mapping and factory; whichever task next needs to update those fields
 * (T24's exchange for {@code lastUsedAt}, T26's revoke for {@code revokedAt}, T26's rename if any
 * for {@code name}) adds the mutator then, following whatever concurrency shape that behavior
 * actually needs (see {@code RecoveryCodeRepository#markUsed} for this codebase's precedent on
 * race-safe single-field updates via a conditional repository query rather than a plain setter).</p>
 */
@Entity
@Table(name = "api_keys")
public class ApiKey {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "key_uuid", nullable = false, unique = true, updatable = false)
    private UUID keyUuid;

    @Column(name = "account_id", nullable = false, updatable = false)
    private Long accountId;

    @Column(name = "prefix", nullable = false, length = 16, updatable = false)
    private String prefix;

    /** CHAR(64), not VARCHAR - JdbcTypeCode.CHAR matches how Postgres reports this column's type
     * (bpchar) so Hibernate's schema validation accepts it. Mirrors RecoveryCode.codeHash. */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "key_hash", nullable = false, unique = true, length = 64, updatable = false, columnDefinition = "char(64)")
    private String keyHash;

    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /** Postgres TEXT[] - no other entity in this schema maps an array column; validated against
     * the real column by ApiKeyPersistenceIntegrationTest, not assumed. */
    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "scopes", nullable = false)
    private List<String> scopes;

    @Column(name = "last_used_at")
    private Instant lastUsedAt;

    @Column(name = "expires_at")
    private Instant expiresAt;

    @Column(name = "revoked_at")
    private Instant revokedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected ApiKey() {
        // JPA only
    }

    /** Timestamps are supplied by the caller, sourced from the injected {@code Clock} — never
     * {@code Instant.now()} inline and never a {@code @PrePersist} lifecycle callback; the DB's
     * {@code created_at DEFAULT now()} exists only as a safety net and is never relied upon here.
     * {@code keyUuid} is generated by this factory, not the caller — it is an internal handle
     * (external identity for API keys is the key material itself, not this UUID). A null
     * {@code scopes} defaults to an empty, mutable list rather than being rejected. */
    public static ApiKey create(Long accountId, String prefix, String keyHash, String name,
                                 List<String> scopes, Instant createdAt) {
        Objects.requireNonNull(accountId, "accountId must not be null");
        Objects.requireNonNull(prefix, "prefix must not be null");
        Objects.requireNonNull(keyHash, "keyHash must not be null");
        Objects.requireNonNull(name, "name must not be null");
        Objects.requireNonNull(createdAt, "createdAt must not be null");

        ApiKey apiKey = new ApiKey();
        apiKey.keyUuid = UUID.randomUUID();
        apiKey.accountId = accountId;
        apiKey.prefix = prefix;
        apiKey.keyHash = keyHash;
        apiKey.name = name;
        apiKey.scopes = scopes != null ? new ArrayList<>(scopes) : new ArrayList<>();
        apiKey.createdAt = createdAt;
        return apiKey;
    }

    public Long getId() {
        return id;
    }

    public UUID getKeyUuid() {
        return keyUuid;
    }

    public Long getAccountId() {
        return accountId;
    }

    public String getPrefix() {
        return prefix;
    }

    public String getKeyHash() {
        return keyHash;
    }

    public String getName() {
        return name;
    }

    public List<String> getScopes() {
        return scopes;
    }

    public Instant getLastUsedAt() {
        return lastUsedAt;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public Instant getRevokedAt() {
        return revokedAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
