package com.themistra.auth.apikey;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * A merchant API key (R30, L7). {@code accountId} is a plain column, never a JPA relation to
 * {@code Account} — this module never imports that entity (L12). {@code keyHash} is the SHA-256
 * hex digest of the full {@code ck_live_<suffix>.<secret>} string; the plaintext key itself is
 * never persisted anywhere. {@code prefix} is {@code VARCHAR(32)} (widened from the original
 * {@code VARCHAR(16)} by T24's {@code V7} migration, to actually fit L7's 32-character public
 * prefix format).
 *
 * <p>Deliberately has no mutators for {@code lastUsedAt}, {@code revokedAt}, or {@code name} —
 * updates to those fields go through {@code ApiKeyRepository}'s conditional
 * {@code @Modifying} queries ({@code updateLastUsedAt}, {@code revokeIfActive}, added by T24),
 * not entity mutators, the same race-safety precedent {@code RecoveryCodeRepository#markUsed}
 * established. A mutator for {@code name} remains unaddressed — no task yet needs to rename a key.</p>
 */
@Entity
@Table(name = "api_keys")
public class ApiKey {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "key_uuid", nullable = false, unique = true, updatable = false)
    private UUID keyUuid;

    @Column(name = "account_id", nullable = false, updatable = false)
    private Long accountId;

    @Column(name = "prefix", nullable = false, length = 32, updatable = false)
    private String prefix;

    /** CHAR(64), not VARCHAR - JdbcTypeCode.CHAR matches how Postgres reports this column's type
     * (bpchar) so Hibernate's schema validation accepts it. Mirrors RecoveryCode.codeHash. */
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "key_hash", nullable = false, unique = true, length = 64, updatable = false, columnDefinition = "char(64)")
    private String keyHash;

    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /** Postgres TEXT[] - no other entity in this schema maps an array column; validated against
     * the real column by ApiKeyPersistenceIntegrationTest, not assumed. */
    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "scopes", nullable = false)
    private List<String> scopes;

    @Column(name = "last_used_at")
    private Instant lastUsedAt;

    @Column(name = "expires_at")
    private Instant expiresAt;

    @Column(name = "revoked_at")
    private Instant revokedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected ApiKey() {
        // JPA only
    }

    /** Timestamps are supplied by the caller, sourced from the injected {@code Clock} — never
     * {@code Instant.now()} inline and never a {@code @PrePersist} lifecycle callback; the DB's
     * {@code created_at DEFAULT now()} exists only as a safety net and is never relied upon here.
     * {@code keyUuid} is generated by this factory, not the caller — it is an internal handle
     * (external identity for API keys is the key material itself, not this UUID). A null
     * {@code scopes} defaults to an empty list rather than being rejected; individual null
     * elements within a non-null {@code scopes} are rejected, since the column is {@code NOT
     * NULL} — the meaning of a blank/empty-string scope, if any, is left to whichever task
     * defines the actual scope vocabulary (T24), not decided here. */
    public static ApiKey create(Long accountId, String prefix, String keyHash, String name,
                                 List<String> scopes, Instant createdAt) {
        Objects.requireNonNull(accountId, "accountId must not be null");
        Objects.requireNonNull(prefix, "prefix must not be null");
        Objects.requireNonNull(keyHash, "keyHash must not be null");
        Objects.requireNonNull(name, "name must not be null");
        Objects.requireNonNull(createdAt, "createdAt must not be null");

        ApiKey apiKey = new ApiKey();
        apiKey.keyUuid = UUID.randomUUID();
        apiKey.accountId = accountId;
        apiKey.prefix = prefix;
        apiKey.keyHash = keyHash;
        apiKey.name = name;
        if (scopes != null) {
            scopes.forEach(scope -> Objects.requireNonNull(scope, "scopes must not contain null elements"));
        }
        apiKey.scopes = scopes != null ? new ArrayList<>(scopes) : new ArrayList<>();
        apiKey.createdAt = createdAt;
        return apiKey;
    }

    public Long getId() {
        return id;
    }

    public UUID getKeyUuid() {
        return keyUuid;
    }

    public Long getAccountId() {
        return accountId;
    }

    public String getPrefix() {
        return prefix;
    }

    public String getKeyHash() {
        return keyHash;
    }

    public String getName() {
        return name;
    }

    /** Returns a defensive, unmodifiable copy — the caller cannot mutate the entity's stored
     * scopes (and inadvertently trigger a persisted update) through it. */
    public List<String> getScopes() {
        return List.copyOf(scopes);
    }

    public Instant getLastUsedAt() {
        return lastUsedAt;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public Instant getRevokedAt() {
        return revokedAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
