package com.themistra.notification.inapp;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * Persisted in-app notification - maps onto {@code notifications.inapp_notifications}, already
 * migrated by T02's own {@code V1__notifications_baseline.sql}. The first entity-backing task in
 * this pipeline needing zero new Flyway migration - the table has waited, fully shaped, since
 * launch.
 *
 * <p>A single public constructor takes every field except {@code id} (generated) and an explicit
 * {@code createdAt} - mirrors {@code DeliveryLog}'s own established precedent (T11): the caller
 * ({@code InAppChannel}) passes {@code clock.instant()}, never the column's own DB-level
 * {@code DEFAULT now()}. {@code notificationUuid} is generated by the caller
 * ({@code UUID.randomUUID()}), the first entity in this module minting a brand-new external
 * identifier itself rather than receiving one from an inbound event. {@code readAt} is always
 * {@code null} at construction - marking a notification read is out of this task's own scope.</p>
 */
@Entity
@Table(name = "inapp_notifications", schema = "notifications")
public class InappNotification {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "notification_uuid", nullable = false, unique = true)
    private UUID notificationUuid;

    @Column(name = "account_uuid", nullable = false)
    private UUID accountUuid;

    @Column(name = "category", nullable = false)
    private String category;

    @Column(name = "title", nullable = false)
    private String title;

    @Column(name = "body", nullable = false)
    private String body;

    @Column(name = "link")
    private String link;

    @Column(name = "read_at")
    private Instant readAt;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    protected InappNotification() {
        // JPA only
    }

    public InappNotification(UUID notificationUuid, UUID accountUuid, String category, String title,
                              String body, String link, Instant createdAt) {
        this.notificationUuid = notificationUuid;
        this.accountUuid = accountUuid;
        this.category = category;
        this.title = title;
        this.body = body;
        this.link = link;
        this.readAt = null;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return id;
    }

    public UUID getNotificationUuid() {
        return notificationUuid;
    }

    public UUID getAccountUuid() {
        return accountUuid;
    }

    public String getCategory() {
        return category;
    }

    public String getTitle() {
        return title;
    }

    public String getBody() {
        return body;
    }

    public String getLink() {
        return link;
    }

    public Instant getReadAt() {
        return readAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * The one shared DTO shape both {@code InappStreamController} and {@code InappReadController}
     * serialize (frozen brief AC10) - nested here, not a separate top-level file, since the entity
     * is its own most natural owner and the frozen brief authorized no additional file for it.
     */
    public record View(UUID notificationUuid, String category, String title, String body,
                        String link, Instant createdAt) {
    }

    public View toView() {
        return new View(notificationUuid, category, title, body, link, createdAt);
    }
}
